### ISSUE TITLE
FindFiles() fails if path is a symlink to a directory.

### ISSUE THREAD

**Issue by marcopaganini** [muesli/gitcha#2]
I've downloaded glow (a CLI markdown viewer) and was puzzled why it didn't show the markdown files in a local repo copy of a private repo where I keep markdown notes. That project uses gitcha to read the files and I ended up tracing the problem here.

In FindFilesExcept() the program explicitly checks if the path is a directory and returns an error. Problem is: Path can be a symlink to a directory (or a symlink to a symlink to a directory, you get  the idea).

I wrote a small function to recurse over the entire symlink chain of a given path until it reaches the "bottom" of the chain. I could send you a PR. Please let me know if this is a desirable fix.

**Comment by muesli** [comment]
Yeah, would love to see a PR for this!

**Comment by marcopaganini** [comment]
Sent https://github.com/muesli/gitcha/pull/3 (above). Please let me know if you're prefer me to squash it before sending.
